server:
  port: "8080"
  api-key: "My-Ap1-k3y"
redis:
  ## host.docker.internal:6379 when app is running locally using docker-compose
  address: "host.docker.internal:6379"
ads:
  url: "https://gist.githubusercontent.com/victorhurdugaci/22a682eb508e65d97bd5b9152f564ab3/raw/dbf27ef217dba9bbd753de26cdabf8a91bdf1550/sm_ads.json"